In [5]:
import torch
import numpy as np
import warnings
warnings.filterwarnings('ignore')

print("torch version: ", torch.__version__)
print("numpy version: ", np.__version__ )

torch version:  2.6.0+cpu
numpy version:  2.2.1


In [8]:
device = "cuda" if torch.cuda.is_available() else "cpu"

my_tensor = torch.tensor([[1,2,3],[4,5,6]], dtype=torch.float32, device=device)

print(my_tensor)
print("Data Type: ", my_tensor.dtype)
print("Device: ", my_tensor.device)
print("shape: ", my_tensor.shape)
print("Requires Gradient:", my_tensor.requires_grad)

tensor([[1., 2., 3.],
        [4., 5., 6.]])
Data Type:  torch.float32
Device:  cpu
shape:  torch.Size([2, 3])
Requires Gradient: False


In [13]:
# creating an empty tensor of size 3,3

x = torch.empty(3,3)
print("empty tensor:\n",x)

empty tensor:
 tensor([[2.5186e+35, 1.0131e-42, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00]])


In [17]:
# createing a tensor filled with zeroes

x = torch.zeros(3,3)
print("Zeros tensor:\n", x)

Zeros tensor:
 tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])


In [21]:
# creating tensor with random values

x = torch.rand(3,3)
print("Random values:\n", x)

Random values:
 tensor([[0.3474, 0.9382, 0.2015],
        [0.0498, 0.1685, 0.2187],
        [0.1700, 0.4837, 0.2991]])


In [23]:
# creating tensors filled with ones

x = torch.ones(3,3)
print("Ones tensors:\n", x)

Ones tensors:
 tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])


In [25]:
# creating an identity matrix

x = torch.eye(3,3)
print("identity matrix:\n", x)

identity matrix:
 tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])


In [27]:
# create a tensor using arrange

x = torch.arange(5)
print("Arange tensor:\n", x)

Arange tensor:
 tensor([0, 1, 2, 3, 4])


In [34]:
# linespace

x = torch.linspace(0.1,1,12)
print(x)


tensor([0.1000, 0.1818, 0.2636, 0.3455, 0.4273, 0.5091, 0.5909, 0.6727, 0.7545,
        0.8364, 0.9182, 1.0000])


In [40]:
# creating a tensor with values drawn from a normal distribution 

x = torch.empty(1,5).normal_(mean=1, std=1)
print(x)

tensor([[ 1.2304, -0.9471,  0.9863,  0.2832, -0.3722]])


In [43]:
x = torch.empty(1,5).uniform_(0,1)
print(x)

tensor([[0.9565, 0.8432, 0.0286, 0.6959, 0.5612]])
